---
title: "scNMT-seq multi-omics analysis"
output:
  html_document:
        toc: yes
params:
  on_mac: !r Sys.info()["user"] == "alabadi"
  on_hpc: !r Sys.info()["user"] != "alabadi"
  cache: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = params$cache)
```

```{r, eval=TRUE}
## ----------- source utils ----------- 
## list all R files in utils folder recursively
utls <- list.files("../src/utils", pattern = ".R", full.names = TRUE, recursive = TRUE)
## source all
invisible(sapply(utls, source))
```

# Packages

```{r}
pkgs <-
  c("mixOmics",
    "data.table",
    "scater",
    "magrittr",
    "here",
    "purrr",
    "scran",
    "uwot",
    "MultiAssayExperiment")
```

```{r installer, message = FALSE, results='hide'}
if (params$on_hpc) {
  .libPaths("~/R_libs")
}
invisible(installer(pkgs = pkgs))
```

```{r max-vsize, eval=params$on_mac, echo=FALSE}
file.create(".Renviron")
cat("R_MAX_VSIZE=50Gb", file = ".Renviron")
```


```{r load-packages, results='hide'}
## load packages
sapply(X = pkgs, FUN = function(package) {
  suppressMessages(library(package, character.only = TRUE, verbose = FALSE, logical.return = TRUE))
  })
```


# Data

```{r read-mae}
gastru_mae <- readRDS(here("output","scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds"))
```

# mixOmics

```{r, include=FALSE}
experiments(gastru_mae) %>% names() %>% dput()
c("rna", "met_genebody", "met_promoter", "met_cgi", "met_p300", 
"met_CTCF", "met_DHS", "acc_genebody", "acc_promoter", "acc_cgi", 
"acc_p300", "acc_CTCF", "acc_DHS")
```

```{r}
## function to get a named list of N x P assays for mixOmics block functions
get_assays <- function(assay_types = c("rna", "met_p300")) {
  lapply(as.list(experiments(gastru_mae)[c("rna", "met_p300")]), t)
}
## sample meta data
meta.data <- colData(gastru_mae)
```

## p300 enhancer sites and expresion

```{r}
tune.block.splsda(X = get_assays(c("rna", "met_p300")), Y = meta.data$stage)
```

