---
title: "scnmtseq-gastrulation create MAE"
output: html_document
params:
  on_hpc: yes
---

# MultiAssayExperiment

## packages

```{r}
suppressMessages(library(data.table))
suppressMessages(library(SingleCellExperiment))
suppressMessages(library(purrr))
suppressMessages(library(magrittr))
suppressMessages(library(mixOmics))
```

## utils

```{r}
utilz <- list.files("/Users/alabadi/Projects/analysis/R/multiOmics/scNMT_seq_gatrulation/src/utils", pattern = "*.R", full.names = TRUE)
invisible(sapply(utilz, source))
```

## load data

```{r}
sce <- readRDS("/Users/alabadi/Projects/analysis/R/multiOmics/Ricard/scNMT_gastrulation/data/gastrulation/rna/parsed/SingleCellExperiment.rds")
met_dt_list <- readRDS("/Users/alabadi/Projects/analysis/R/multiOmics/scNMT_seq_gatrulation/output/met_dt_list.rds")
acc_dt_list <- readRDS("/Users/alabadi/Projects/analysis/R/multiOmics/scNMT_seq_gatrulation/output/acc_dt_list.rds")
```
```{r}
sample_metadata <- fread("/Users/alabadi/Projects/analysis/R/multiOmics/scNMT_seq_gatrulation/data/gastrulation/sample_metadata.txt") %>% 
  .[pass_metQC==TRUE & pass_rnaQC==TRUE  & pass_accQC==TRUE ] %>% 
  .[,c("sample","id_met","id_acc","id_rna","stage","lineage10x_2")] %>%
  .[,stage_lineage:=as.factor(paste(stage,lineage10x_2,sep="_"))]
```


## spread id ~ sample by rate

```{r}
dcast_met <- dcast_dt_list(met_dt_list, row = "id", col = "id_met", value.var = "rate")
dcast_acc <- dcast_dt_list(acc_dt_list, row = "id", col = "id_acc", value.var = "rate")
```

### change expression sample names

```{r, eval=TRUE}
## rename id_rna for sce
sce <- sce[,sample_metadata$id_rna]
# id_map <- sample_metadata[,c("sample", "id_rna")] %>% data.frame(row.names = 2)
# colnames(sce) <- id_map[colnames(sce),]
```
## make MAE

```{r}
data_list <- list(
  rna = logcounts(sce)

  met_genebody = dcast_met$Genebody[,sample_metadata$id_rna],
  met_promoter = dcast_met$Promoters[,sample_metadata$id_rna],
  met_cgi = dcast_met$CGI[,sample_metadata$id_rna],
  met_p300 = dcast_met$p300[,sample_metadata$id_rna],
  met_CTCF = dcast_met$CTCF[,sample_metadata$id_rna],
  met_DHS = dcast_met$DHS[,sample_metadata$id_rna],
  acc_genebody = dcast_acc$Genebody[,sample_metadata$id_rna],
  acc_promoter = dcast_acc$Promoters[,sample_metadata$id_rna],
  acc_cgi = dcast_acc$CGI[,sample_metadata$id_rna],
  acc_p300 = dcast_acc$p300[,sample_metadata$id_rna],
  acc_CTCF = dcast_acc$CTCF[,sample_metadata$id_rna],
  acc_DHS = dcast_acc$DH[,sample_metadata$id_rna]
)
```

```{r}
library(MultiAssayExperiment)

exper.list <- ExperimentList(
  rna = logcounts(sce),
                           
                           met_genebody = dcast_met$Genebody,
                           met_promoter = dcast_met$Promoters,
                           met_cgi = dcast_met$CGI,
                           met_p300 = dcast_met$p300,
                           met_CTCF = dcast_met$CTCF,
                           met_DHS = dcast_met$DHS,
                           
                           acc_genebody = dcast_acc$Genebody,
                           acc_promoter = dcast_acc$Promoters,
                           acc_cgi = dcast_acc$CGI,
                           acc_p300 = dcast_acc$p300,
                           acc_CTCF = dcast_acc$CTCF,
                           acc_DHS = dcast_acc$DHS
                           )
```

```{r}
exper.list <- lapply(exper.list, function(x){
  colnames(x) <- sample_metadata$sample
})
```


```{r}
all_identical <- function(lst) {
  if (is.null(names(lst))) {
    names(lst) <- seq_along(lst)
  }
  for (j in seq_along(lst[-1])) {
    if (!identical(lst[[j]], lst[[j+1]]))
      stop(sprintf("not identical elements: %s", paste(names(lst)[c(j, j+1)], collapse = " & ")), call. = FALSE)
  }
  TRUE
}
```

```{r}
all.identical(lapply(exper.list, colnames))
```


```{r}
coldata <- sample_metadata %>% data.frame(row.names = TRUE) %>% .[,c("stage", "lineage10x_2", 
"stage_lineage")] %>% DataFrame()
scnmtseq_gastrulation_mae <- MultiAssayExperiment(experiments = exper.list, colData = coldata)
```


```{r}
saveRDS(scnmtseq_gastrulation_mae, file= "/Users/alabadi/Projects/analysis/R/multiOmics/scNMT_seq_gatrulation/__Hackathon/Preparation_hackathon/scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds")
```

<!-- Add decomposed (biological) variance to rna for HVGS selection: -->

```{r}
# scnmtseq_gastrulation_mae <- readRDS("../output/scnmtseq_gastrulation_mae.rds")
```

```{r}
# sce <- readRDS("../data/gastrulation/rna/parsed/SingleCellExperiment.rds")
# rowData(sce)
```

```{r}
library(scran)
fit <- trendVar(sce, use.spikes=FALSE)
decomp.var <- decomposeVar(sce, fit = fit)
library(ggplot2)
ggplot(as.data.frame(decomp.var)) + geom_point(aes(x=mean, y=total), alpha=0.6) + theme_bw()
ggplot(as.data.frame(decomp.var)) + geom_point(aes(x=mean, y=bio), alpha=0.6) + theme_bw()
```

```{r}
## add to rowData
rowData(sce) <- cbind(rowData(sce), decomp.var[,c("bio", "total")])
```

```{r}
library(MultiAssayExperiment)

exper.list <- ExperimentList(rna = sce,
                           experiments(scnmtseq_gastrulation_mae)[-1]
                           )

MultiAssayExperiment(experiments = exper.list, colData = colData(scnmtseq_gastrulation_mae))

coldata <- sample_metadata %>% data.frame(row.names = TRUE) %>% .[,c("stage", "lineage10x_2", 
"stage_lineage")] %>% DataFrame()
scnmtseq_gastrulation_mae <- MultiAssayExperiment(experiments = exper.list, colData = coldata)
scnmtseq_gastrulation_mae <- MatchedAssayExperiment(mae_scnmt_seq)

coldata <- sample_metadata %>% data.frame(row.names = TRUE) %>% .[,c("stage", "lineage10x_2", 
"stage_lineage")] %>% DataFrame()
scnmtseq_gastrulation_mae <- MultiAssayExperiment(experiments = exper.list, colData = coldata)
scnmtseq_gastrulation_mae <- MatchedAssayExperiment(mae_scnmt_seq)
```

```{r, eval=FALSE}
knitr::purl("scnmtseq-gastrulation.Rmd",documentation = 1L, output = "../src/scnmtseq-gastrulation.R")
```

