---
title: "Single Omics NIPALS"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
  nipals_ncomp: 2
  # grad_cols: !r c(low = "darkblue", high = "orange")
  subset: !r c(20, 400)
  rerun: false
  saveRDS: false
  repeat_runs: 1
  props_NA: !r c(0)
  scale: FALSE
output:
  html_document:
    toc: true
---

TODO

* Trello >> scNMTseq >> weights benchmarking

```{r}
dput(params)
```

```{r, warning=FALSE, message=FALSE}
library(nipals)
library(mixOmics)
library(reticulate)
library(umap)
library(here)
library(ggplot2)
library(parallel)
library(MultiAssayExperiment)
library(magrittr)

invisible(sapply(list.files(here('src', 'utils'), pattern = "*.R", full.names = TRUE), source))
```

# Data

load MAE and keep only main lineages

```{r load-data}
# load(url("https://github.com/LuyiTian/sc_mixology/blob/master/data/sincell_with_class.RData?raw=true"))
# saveRDS(sce_sc_10x_qc, file = here("output", "cellbench-10x.rds"))
suppressMessages({
  mae <- readRDS(here("output", "scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds"))
  # dput(unique(mae$lineage10x_2))
  mae <- mae[,mae$lineage10x_2 %in% c("Epiblast", "Mesoderm", "Endoderm", "Ectoderm"),]
})

```

```{r}
# stratified_subsample_mae <- function(mae, pheno = "lineage10x_2", n_samples = 100) {
#   library(dplyr)
#   cd <- colData(mae) %>% data.frame %>% group_by_(pheno) %>% mutate()
#   phenos <- cd[,pheno]
#   n_classes <- table(cd)
#   classes <- names(n_classes)
#   props <- n_classes/sum(n_classes)
#   for (clas in classes) {
#     
#   }
# }
```


```{r}
source(here("src", "nipals-utils.R"))
```

# Effects of normalising weights

subset assay data, if necessary

```{r}
assay_name <- "met_promoter"
mae_assay_data <- get_assay_subset(mae = mae, assay_name = assay_name, pheno = c("day", "lineage10x_2"), subset = params$subset)
```

unscaled weights summary:

```{r}
summary(mae_assay_data$weights[1,])
hist(mae_assay_data$weights[1,])
```
```{r}
empca_wrapper_norm <- function(mae_assay_data, gramshmidt=FALSE, norm_weights = TRUE, ncomp = 2, scale = FALSE) {
  
  mae_assay_data$weights_norm <- mae_assay_data$weights/max(mae_assay_data$weights, na.rm = TRUE)
  
  nipals_runtime <- system.time({
    nipals_res <- nipals::nipals(x = mae_assay_data$dataset, ncomp = ncomp, center = TRUE, scale = scale, gramschmidt = gramshmidt, fitted = FALSE)
  })['elapsed']
  
  empca_runtime <- system.time({
    empca_res <- nipals::empca(x = mae_assay_data$dataset, w = mae_assay_data$weights, ncomp = ncomp, center = TRUE, scale = scale, gramschmidt = gramshmidt, fitted = FALSE)
  })['elapsed']
  
  empca_norm_runtime <- system.time({
    empca_norm_res <- nipals::empca(x = mae_assay_data$dataset, w = mae_assay_data$weights_norm, ncomp = ncomp, center = TRUE, scale = scale, gramschmidt = gramshmidt, fitted = FALSE)
  })['elapsed']
  
  list(
    empca = list(result = empca_res, runtime = empca_runtime),
    empca_norm = list(result = empca_norm_res, runtime = empca_norm_runtime),
    nipals = list(result = nipals_res, runtime = nipals_runtime)
  )
}
```

EMPCA with unscaled vs normalised weights:

```{r}
pca_res <- empca_wrapper_norm(mae_assay_data, gramshmidt = FALSE)
```

See if results are the same:

```{r}
mapply(FUN = function(x, y) {
  testthat::expect_equal(x, y)
  TRUE
}, x = pca_res$empca$result, y = pca_res$empca_norm$result)
```

# Performance

For RNA data, we:
- keep top genes with high mean expression:

```{r}
rna <- assay(mae, "rna") %>% t()
```

```{r}
library(pheatmap)
compare_pca <- function(dataset = rna, np_subset = c(30, 100), min_expr = 4, seed = 100,
                        prop_NA = 0.2){
  ## mean lognormalised expr greater than 3
  mat=dataset %>% .[,colMeans(.)>min_expr] %>% subset_please(np_subset = np_subset) %>% .$dataset
  mat[mat == 0] <- 0.01
  set.seed(seed)
  variances <- rlnorm(n = length(mat),meanlog = log(0.1), sdlog = 1)
  variances <- matrix(variances, nrow = nrow(mat))
  
  construct_est_mat <- function(mat, wt) {
    res <- mapply(x=as.vector(mat), y=as.vector(wt), FUN = function(x, y){
      rlnorm(n = 1, meanlog = log(x), sdlog = sqrt(1/y))
    }) 
    res <- matrix(res, nrow = nrow(mat), dimnames = dimnames(mat))
    # res[res>max(mat)+iqr(mat)] <- max(mat)+iqr(mat)
    res
  }
  
  weights <- matrix(1/variances, nrow = nrow(mat))
  est_mat <- construct_est_mat(mat = mat, wt = weights)
  
  heatmaps <- function(mat, est_mat, weights) {
    # for matrix, estimated matrix and weights create
    # heatmaps where ranges are equal
    
    shift_matrix_range <- function(mat, ref_mat) {
      ## take matrix range = [a, b] to [d, e] using [a, b]*C1 + C2
      c1 <- diff(range(ref_mat))/diff(range(mat))
      c2 <- min(ref_mat) - min(mat)*c1
      mat*c1 + c2
    }
    hmap_col <- colorRampPalette(rev(brewer.pal(n = 7, name =
  "RdYlBu")))(100)
    vars <- 1/weights
    mat_diff <- abs(est_mat-mat)
    mat_diff_viz <- mat_diff
    # mat_diff_viz[mat_diff_viz > mat + 3*sqrt(vars)] <- as.double("NA")
    mat_diff_viz <- (mat_diff_viz/max(mat_diff_viz, na.rm = TRUE))

    dimnames(mat_diff_viz) <- NULL
    pheatmap(mat_diff_viz, color = hmap_col, cluster_cols = FALSE, cluster_rows = FALSE, annotation_row = NULL, main = "Deviation from original values - standardised")
    adjusted_vars <- shift_matrix_range(mat = vars, ref_mat = mat_diff_viz)
    dimnames(adjusted_vars) <- NULL
    pheatmap(adjusted_vars, color = hmap_col, cluster_cols = FALSE, cluster_rows = FALSE, main = "sampling dispersion - standardised")
    cor.test(as.vector(mat_diff),as.vector(vars))
  }
  heatmaps(mat, est_mat, weights)
# 
#   est_mat_with_na <- rand_na(est_mat, prop = prop_NA)
#   weights[is.na(est_mat_with_na)] <- NA
#   true_pca <- nipals::nipals(mat, ncomp = 2, center = TRUE, scale = FALSE, gramschmidt = FALSE)
#   nipals <- nipals::nipals(est_mat_with_na, ncomp = 2, center = TRUE, scale = FALSE, gramschmidt = FALSE, fitted = TRUE)
#   empca <- nipals::empca(est_mat_with_na, w = weights, ncomp = 2, center = TRUE, scale = FALSE, gramschmidt = FALSE, fitted = TRUE)
#   sum(abs(nipals$fitted - mat))
#   sum(abs(empca$fitted - mat))
#   return(list(mat = mat, nipals = nipals, empca = empca))
}
```

```{r}
compare_pca(dataset = rna)
```


