---
title: "Single Omics NIPALS"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
  nipals_ncomp: 2
  # grad_cols: !r c(low = "darkblue", high = "orange")
  subset: !r c(0, 0)
  rerun: false
  saveRDS: false
  repeat_runs: 1
  props_NA: !r c(0)
  scale: FALSE
output:
  html_document:
    toc: true
---

```{r}
dput(params)
```

```{r, warning=FALSE, message=FALSE}
library(nipals)
library(mixOmics)
library(reticulate)
library(umap)
library(here)
library(ggplot2)
library(parallel)
library(MultiAssayExperiment)
library(magrittr)

invisible(sapply(list.files(here('src', 'utils'), pattern = "*.R", full.names = TRUE), source))
```

# Data

```{r load-data, eval=params$rerun}
# load(url("https://github.com/LuyiTian/sc_mixology/blob/master/data/sincell_with_class.RData?raw=true"))
# saveRDS(sce_sc_10x_qc, file = here("output", "cellbench-10x.rds"))
suppressMessages({
  mae <- readRDS(here("output", "scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds"))
})

```

```{r}
source(here("src", "nipals-utils.R"))
```


# Epigenome Data

## runtime with limited number of features

```{r epi-data, eval=params$rerun}
bm_datasets_res <- list()
epi_data <- names(mae)[-1] %>% .[!grepl(pattern = "^wt*", .)]

bm_datasets_res[epi_data] <- mclapply(named_list(epi_data), FUN = function(data_name) {
  dataset <- assay(mae, data_name) %>% t()
  weights <- assay(mae, paste0("wt_",data_name)) %>% t()
  pheno = mae$day
  
  props_NA <- c(0)
  repeat_runs <- params$repeat_runs
  subset <- params$subset
  ncomp = params$nipals_ncomp
  
  res <- benchmark_nipals(dataset = dataset, weights = weights, props = props_NA, pheno = pheno, subset = subset, ncomp = ncomp, microbench = FALSE, scale = params$scale)
  out_file <- here("output", "tmp", sprintf("nipals-benchamrk-%s.rds", data_name))
  if(dir.exists(dirname(out_file))) {
    saveRDS(res, file = here("output", "tmp", sprintf("nipals-benchamrk-%s.rds", data_name)))
  }
  res
}, mc.cores = detectCores())

```

```{r epi-data-read, eval=FALSE}
# bm_datasets_res <- list()
# epi_data <- names(mae)[-1] %>% .[!grepl(pattern = "^wt*", .)]
# for (data_name in epi_data) {
#   bm_datasets_res[[data_name]] <- readRDS(here("output", "tmp", sprintf("nipals-benchamrk-%s.rds", data_name)))
# }
```

```{r}
scaled <- ifelse(params$scale, "scaled", "unscaled")
empca_rds_name <- here("output", sprintf("empca-vs-nipals-for-gastru-data_top-%s-features-%s.rds", params$subset[2], scaled))
```

```{r saveruns2, eval=params$rerun&params$saveRDS}
saveRDS(bm_datasets_res[epi_data], file = empca_rds_name)
```

## EMPCA vs NIPALS

```{r, eval=!params$rerun}
empca_rds_name <- list.files(here("output"), pattern = "^empca-vs", full.names = TRUE)[1]
bm_datasets_res <- readRDS(empca_rds_name)
```


```{r, eval=!params$rerun}
all_epi_plots <- lapply(named_list(names(bm_datasets_res)), function(data_name) {
  show_benchmark_res(bm_res = bm_datasets_res[[data_name]], which = 1, empca = TRUE, subtitle = data_name)
})
all_epi_plots
```

## Scale Weights


```{r, eval=!params$rerun}
empca_rds_name <- list.files(here("output"), pattern = "^empca-vs.*unscaled*", full.names = TRUE)[1]
bm_datasets_res <- readRDS(empca_rds_name)
```


```{r, eval=!params$rerun}
all_epi_plots <- lapply(named_list(names(bm_datasets_res)), function(data_name) {
  show_benchmark_res(bm_res = bm_datasets_res[[data_name]], which = 1, empca = TRUE, subtitle = data_name)
})
all_epi_plots
```

