---
title: "Single Omics"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
  nipals_ncomp: 20
  grad_cols: !r c(low = "darkblue", high = "orange")
output:
  html_document:
    toc: true
---

```{r, warning=FALSE, message=FALSE}
library(MultiAssayExperiment)
library(reticulate)
library(nipals)
library(mixOmics)
library(umap)
library(here)
library(ggplot2)
```


## utils

```{r utls}
## ----------- source utils ----------- 
## list all R files in utils folder recursively
utls <- list.files(file.path(io$home, "src/utils"), pattern = ".R", full.names = TRUE, recursive = TRUE)
## source all
invisible(sapply(utls, source))
```

# Data

```{r}
gastru.mae <- readRDS(here('output/scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds'))  # MAE experiment
gastru.mae
```

## designate assays

```{r}
study_assays <- c("met_promoter", "acc_promoter", "rna", "met_genebody", "acc_genebody")
# study_assays <- c("rna", "met_genebody", "met_promoter", "met_cgi",  "acc_promoter", "acc_cgi",  "acc_p300", "acc_CTCF", "acc_DHS")
```


```{r}
study_mae <- gastru.mae[,,study_assays]
study_mae <- study_mae[,(study_mae$day %in%  c(7.5))
                       & (study_mae$lineage10x_2 %in% c("Epiblast", "Mesoderm", "Endoderm", "Ectoderm"))
                      ,]
coldata <- data.frame(colData(study_mae))
# coldata$lineage10x_2[is.na(coldata$lineage10x_2)] <- "Unknown"
```

Get all P x N matrices:

```{r}
X <- lapply(named_list(study_assays), function(assay_i){
  out <- assay(study_mae, assay_i)
  colnames(out) <- paste0(colnames(out), '_', assay_i)
  out
})


```

Common features names:

```{r}
comm_genes <- Reduce(intersect, lapply(X, rownames))
X <- lapply(X, function(x) x[comm_genes,])

## rank rna by hvgs
X$rna <- X$rna[order(-rowVars(X$rna)),]
rna_hvgs <- rownames(X$rna[order(-rowVars(X$rna)),])[1:1000]
X <- lapply(X, function(x) x[rna_hvgs,])

# comm_cells <- Reduce(intersect, lapply(X, colnames))
# length(comm_cells)
```

```{r}
# mat <- X$rna[1:400,]
# dist <- dist(mat)
# hclust.res <- hclust(dist)
# plot(hclust.res)
# cim(as.matrix(dist))
# ph <- pheatmap::pheatmap(as.matrix(dist), kmeans_k = 4)
```


block.pls
```{r}
# diablo_genes <- block.splsda(X = X, Y = coldata$lineage10x_2, ncomp = 2, keepX = keepX, mode = 'canonical')
## genes co-varying in the canonical space of phenotypes
X1 <- X[c(1,2,4,5)]
design <- 1-diag(seq_along(X1))
keepX <- lapply(X1, function(x) c(20, 20))
dimnames(design) <- list(names(X1), names(X1))
pls_genes <- block.spls(X = X1, Y = X$rna, ncomp = 4,  mode = 'canonical', design = design, keepX = keepX, keepY = c(20, 20))


plotIndiv(pls_genes, comp = c(1,3), ind.names = FALSE)
```

```{r}
plotIndiv(pls_genes, ind.names = FALSE, pch = 16)
```

```{r}

```

