---
title: "DIABLO using rna, promoter and CTCF"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
output:
  html_document:
    toc: true
---

```{r, warning=FALSE, message=FALSE}
library(MultiAssayExperiment)
library(mixOmics)
library(here)

source(here("src/source-utils.R"))
```


```{r, echo=FALSE}
knitr::opts_chunk$set(eval = TRUE, cache = FALSE)
```

# Data

```{r}
gastru.mae <- readRDS(here('output/scnmtseq_gastrulation_mae_826-cells_orderedFeatures_pearson-residuals_all-rna-ordered.rds'))  # MAE experiment
gastru.mae
```

## designate assays

```{r}
study_assays <- c("rna", "met_promoter", "acc_promoter", "met_CTCF", "acc_CTCF")
```

```{r}
study_mae <- gastru.mae[,,study_assays]

if (params$on_mac) {
  study_mae <- subset_mae(mae = study_mae, samples = 300, max_feat = 250)
}
```


## DIABLO

### design matrix

design matrix to only allow interaction with rna:

```{r}
design <- create_design(mae = study_mae, off_diag = 1)
design
```

### tune


```{r}
tune_diablo_mae <- function(mae, design, ncomp = 2, test.keepX = c(10, 50), Y = NULL, mode = "canonical", folds = 2) {
  
  if (is.null(Y)) {
    Y <- mae$lineage10x_2
  }
  X <- lapply(as.list(experiments(study_mae)), t)
  test.keepX <- create_keepX(mae, keepX = test.keepX)
  
  tune_diablo_res <- tune.block.splsda(X = X, Y = Y, ncomp = ncomp, test.keepX = test.keepX,  design = design, validation = "Mfold", folds = folds, weighted = TRUE, dist = "max.dist", cpus = detectCores())
  tune_diablo_res
}
```

```{r}
folds <- 5
test.keepX = c(5,seq(10,50,10))
ncomp = 2
if (params$on_mac) {
  folds <- 2
  test.keepX = c(1,2)
  ncomp = 2
}
tune_diablo_res <- tune_diablo_mae(mae = study_mae, design = design, ncomp = ncomp, test.keepX = test.keepX, Y = NULL, mode = "canonical", folds = folds)
```

```{r}
if (params$on_hpc) {
  saveRDS2(tune_diablo_res, file = here("output/tune_diablo_res.rds"), suffix = "auto", log = paste0(study_assays, collapse = ", "))
}
```

```{r, echo = FALSE}
## ensure a vector's tails are confined to an interval ( well use confined seach grid instead)
# trim_vec <- function(num_vec = 1:30, min = 10, max = 20){
#   num_vec[num_vec < min] <- min
#   num_vec[num_vec > max] <- max
#   num_vec
# }

## trim choice_ncomp to a min and a max
# get_opt_keepX <- function(tune_diablo_res) {
#   lapply(tune_diablo_res$choice.keepX, trim_vec)
# }
```

### final model

```{r}
run_diablo_mae <- function(mae, design, ncomp = 2, test.keepX = c(10, 50), Y = NULL, mode = "canonical", folds = 2) {
  
  if (is.null(Y)) {
    Y <- mae$lineage10x_2
  }
  X <- lapply(as.list(experiments(study_mae)), t)
  test.keepX <- create_keepX(mae, keepX = test.keepX)
  
  tune_diablo_res <- tune.block.splsda(X = X, Y = Y, ncomp = ncomp, test.keepX = test.keepX,  design = design, validation = "Mfold", folds = folds, weighted = TRUE, dist = "max.dist", cpus = detectCores())
  tune_diablo_res
}
```


```{r}
X <- lapply(as.list(experiments(study_mae)), t)
Y <- study_mae$lineage10x_2
keepX <-tune_diablo_res$choice.keepX
rt <- system.time({
  diablo_res <-
    block.splsda(
      X = X,
      Y = Y,
      ncomp = 2,
      keepX = keepX,
      design = design,
      near.zero.var = TRUE
    )
})
```


### performance of the final model

```{r}
perf.diablo <- perf(diablo_res, folds = 4 , dist = "max.dist", auc = TRUE, cpus = 4)
```



