---
title: "Create assay of certain assays"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
output:
  html_document:
    toc: true
---

```{r, warning=FALSE, message=FALSE}
library(MultiAssayExperiment)
library(here)
source(here("src/source-utils.R"))
```


```{r, echo=FALSE}
knitr::opts_chunk$set(eval = TRUE, cache = FALSE)
```

# Data

```{r}
gastru.mae <- readRDS(here('output/scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds'))  # MAE experiment
gastru.mae
```
```{r}
coldata <- data.frame(colData(gastru.mae))
```


## designate assays

```{r}
study_assays <- c("rna", "met_promoter", "acc_promoter", "met_p300", "acc_p300")
```

```{r}
all_identical <- function(lst) {
  if (is.null(names(lst))) {
    names(lst) <- seq_along(lst)
  }
  for (j in seq_along(lst[-1])) {
    if (!identical(lst[[j]], lst[[j+1]]))
      stop(sprintf("not identical elements: %s", paste(names(lst)[c(j, j+1)], collapse = " & ")), call. = FALSE)
  }
  TRUE
}
```



```{r}
diablo_wrapper <- function(mae, study_assays, do.tune=FALSE, ncomp=2) {
  X <- lapply(named_list(study_assays), function(x) t(assay(mae,x)))
  if (!do.tune) {
    keepX <- c(50, 50)
  }
  
}
```


```{r}
order(rowVars(assay(gastru.mae, "rna")))
```



