---
title: "block.spls scores on umap"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
output:
  html_document:
    toc: true
---

```{r, warning=FALSE, message=FALSE}
library(MultiAssayExperiment)
library(mixOmics)
library(here)
library(knitr)
```


```{r, echo=FALSE}
knitr::opts_chunk$set(eval = TRUE, cache = !FALSE, warning = FALSE, out.width = "100%")
```


```{r}
source(here("src/source-utils.R"))
```

# Data

```{r}
gastru.mae <- readRDS(here('output/scnmtseq_gastrulation_mae_826-cells_orderedFeatures.rds'))  # MAE experiment
gastru.mae <- gastru.mae[,!is.na(gastru.mae$lineage10x_2) & ! (gastru.mae$lineage10x_2 %in% c("ExE_ectoderm")),]
```


check column names are consistent:

```{r}
all_identical(colnames(gastru.mae))
```


```{r}
coldata <- data.frame(colData(gastru.mae))
```

```{r}
rna <- assay(gastru.mae, 'rna')
```

```{r}
library(biomaRt)

ensembl <- useMart("ensembl", dataset="mmusculus_gene_ensembl")
mouse_gene_ids  <- rownames(rna)

symbols <- getBM(attributes=c('ensembl_gene_id',
                          'external_gene_name'),
             filters = "ensembl_gene_id",
             values = mouse_gene_ids,
             mart = ensembl)
symbols <- data.frame(symbols, row.names = 1)
save(symbols, file = 'rna-gene-symbols.RData')
```

```{r}
load('rna-gene-symbols.RData')
```

```{r}
rownames(rna) <- make.unique(symbols[rownames(rna),1])
```


# sPLSDA (rna ~ stage_lineage)

```{r}
splsda.res <- splsda(X = t(rna), Y = coldata$stage, ncomp = 3, keepX = c(50, 50, 50), mode = 'canonical', scale = FALSE)
plotLoadings(splsda.res, comp = 1, contrib = 'max', title = '', legend.title = 'Stage')
plotLoadings(splsda.res, comp = 2, contrib = 'max')
## Regulatory Role of Klf5 (TF) in Early Mouse Development and in Embryonic Stem Cells

## Dppa Developmental pluripotency-associated protein coding genes
## UTF: Undifferentiated Embryonic Cell Transcription Factor coding gene
# tune.splsda.res <- tune.splsda(X = t(rna), Y = coldata$stage, ncomp = 3, test.keepX = c(50, 75, 100), folds = 3, nrepeat = 2, cpus = 3)
# tune.splsda.res$choice.keepX
# plot(tune.splsda.res)
```

```{r}
umap_rna_unsup <- readRDS('../../single-omic/trajectory/umap-result-ncomp-10.rds')
```

```{r}
markers <- selectVar(splsda.res, comp = 1)
markers$name[1]
```

```{r}
gene <- selectVar(splsda.res, comp = 1)$name[1]
ggplot_redDim_expression(arr = umap_rna_unsup$layout, col = rna[gene,], dims = c(3,4), col.legend = gene)
gg_sidebyside_dims(arr = umap_rna_unsup$layout, dims = c(3,4), coldata = coldata)
gene <- selectVar(splsda.res, comp = 2)$name[5]
ggplot_redDim_expression(arr = umap_rna_unsup$layout, col = rna[gene,], dims = c(3,4), col.legend = gene)
```

## designate assays

```{r}
study_assays <- c( "met_promoter", "acc_DHS", "met_genebody", "acc_promoter","met_p300", "acc_p300")
 # study_assays <- c("rna", "met_genebody", "met_promoter", "met_cgi",  "acc_promoter", "acc_cgi",  "acc_p300", "acc_CTCF", "acc_DHS")
```


```{r}
study_mae <- gastru.mae[,,study_assays]
```

## run block.spls

```{r}
X <- lapply(as.list(experiments(study_mae)), t)
X <- suffix_colnames(X, indices = seq_along(X))

# if (params$on_mac) {
#   X <- lapply(X,  subset_pn, p=2000)
# }
lapply(X, dim)
Y <- t(assay(gastru.mae, 'rna'))
```


```{r, eval=params$on_hpc}
design <- create_design(mae = study_mae, off_diag = 0)
ncomp <- 4
keepX <- lapply(X, function(x){
  p <- dim(x)[2]
  keepx <- ifelse(p > 500, 50, 20)
  rep(keepx, ncomp)
  
})

block.spls.res <- block.spls(X = X, Y = Y, ncomp = ncomp, keepX = keepX, scale = FALSE)
saveRDS(block.spls.res, file = here("output/block.spls.res.rds"))
```

```{r}
block.spls.res <- readRDS(here("output/block.spls.res.rds"))
```


```{r}
plotIndiv(block.spls.res, pch=16, , group = study_mae$stage, legend = TRUE, comp = 1:2,  legend.title = "Stage")
plotIndiv(block.spls.res, pch=16, , group = study_mae$stage, legend = TRUE, comp = 2:3,  legend.title = "Stage")
plotIndiv(block.spls.res, pch=16, group = coldata$lineage10x_2, legend = TRUE, comp = 1:2, legend.title = "Lineage")
plotIndiv(block.spls.res, pch=16, group = coldata$lineage10x_2, legend = TRUE, comp = 2:3, legend.title = "Lineage")
```
```{r}
ggplot_redDim_block_comp <- function(block.spls.obj, block, comp=1, title=NULL, umap_arr = umap_rna_unsup$layout) {
  
  LV <- block.spls.obj$variates[[block]][, comp]
  LV <- (LV - min(LV))/ (max(LV) - min(LV))
  LV <- (LV - 0.5)*2
  p <- ggplot_redDim_expression(
    arr = umap_arr,
    col = LV,
    dims = c(3, 4),
    col.legend = paste0('LV-', comp),
    low.col = '#FFC300',
    high.col = '#581845'
  ) +  theme_bw() + theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black")
  )
  p + labs(title = title)
}
```

```{r}
ggplot_redDim_block_comp(block.spls.obj = block.spls.res, block = 'met_promoter', comp = 1, title = 'met_promoter')
ggplot_redDim_block_comp(block.spls.obj = block.spls.res, block = 'acc_DHS', comp = 1, title = 'acc_DHS')
ggplot_redDim_block_comp(block.spls.obj = block.spls.res, block = 'met_genebody', comp = 1, title = 'met_genebody')
ggplot_redDim_block_comp(block.spls.obj = block.spls.res, block = 'acc_p300', comp = 1, title = 'acc_p300')
```

Methylation in promoters and accessibility in p300 enhancers seem to correlate with embryonic days:

```{r}
library(data.table)
coldata_dt <- data.table(coldata, keep.rownames = "cell", check.names = FALSE, stringsAsFactors = FALSE)
selected_features <- selectVar(block.spls.res)[seq_along(X)]
```

### mean rate for selected features by stage

```{r}
boxplot_means <- function(omic, x_lab, y_lab) {
  dt <- data.table(X[[omic]][,selected_features[[omic]]$name], keep.rownames = "cell", check.names = FALSE, stringsAsFactors = FALSE)
  dt <- melt.data.table(dt, variable.name = "feature", value.name = "rate")
  dt <- data.table::merge.data.table(dt, coldata_dt)
  df <- data.frame(dt[,.(mean_rate = mean(rate, na.rm=TRUE)), by = c("day", "feature")])
  df$stage <- paste0("E", df$day)
  ggplot(df, aes(x = stage, y = mean_rate))  +  geom_violin(aes(fill = stage))  +  geom_boxplot(aes(fill = stage), width = 0.1, alpha = 0.4 )  + geom_jitter(width = 0.4, height = 0) +
    labs(x = x_lab, y = y_lab)  +  theme_bw()
}
```

#### promoter methylation


```{r}
boxplot_means(omic = "met_promoter", x_lab = "Embryonic Stage", y_lab = "mean promoter methylation")
```

#### met_promoter

```{r}
boxplot_means(omic = "met_promoter", x_lab = "Embryonic Stage", y_lab = "mean promoter methylation")
```

#### met_genebody

```{r}
boxplot_means(omic = "met_genebody", x_lab = "Embryonic Stage", y_lab = "mean genebody methylation")
```

#### acc_p300

```{r}
boxplot_means(omic = "acc_p300", x_lab = "Embryonic Stage", y_lab = "mean enhancer accessibility")
```

#### acc_DHS

```{r}
boxplot_means(omic = "acc_p300", x_lab = "Embryonic Stage", y_lab = "mean DHS accessibility")
```

# GSEA

https://raw.githack.com/bioFAM/MOFA2/master/MOFA2/vignettes/GSEA.html


```{r}
library(data.table)
library(purrr)
library(ggplot2)
library(cowplot)
library(MOFAdata)
```

```{r}

```

