---
title: "Trajectory analysis with monocole 3"
author: "Al J Abadi"
params:
  on_hpc: !r Sys.info()['user'] != 'alabadi'
  on_mac: !r Sys.info()['user'] == 'alabadi'
  rerun: false
output:
  html_document:
    toc: true
---

# To Do

* Why `devtools::install_github('cole-trapnell-lab/leidenbase')` fails

```{r}
BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats',
                       'limma', 'S4Vectors', 'SingleCellExperiment',
                       'SummarizedExperiment', 'batchelor', 'Matrix.utils'))
```

```{r}
devtools::install_github('cole-trapnell-lab/leidenbase')
devtools::install_github('cole-trapnell-lab/monocle3')
## Fails
```



```{r, warning=FALSE, message=FALSE}
library(MultiAssayExperiment)
library(here)
```


```{r, echo=FALSE}
knitr::opts_chunk$set(eval = TRUE, cache = !FALSE, warning = FALSE, out.width = "100%")
```


```{r}
source(here("src/source-utils.R"))
```

## Data

```{r}
gastru.mae <- readRDS(here('output/scnmtseq_gastrulation_mae_826-cells_orderedFeatures_rna-filtered-sorted.rds'))  # MAE experiment
gastru.mae <- gastru.mae[,!is.na(gastru.mae$lineage10x_2),]
```


## designate assays

```{r}
study_assays <- c("met_promoter", "acc_promoter")
# study_assays <- c("rna", "met_genebody", "met_promoter", "met_cgi",  "acc_promoter", "acc_cgi",  "acc_p300", "acc_CTCF", "acc_DHS")
```


```{r}
study_mae <- gastru.mae[,,study_assays]
# study_mae <- study_mae[,(study_mae$day %in%  c(4.5, 7.5)) 
#                        # & (study_mae$lineage10x_2 %in% c("Epiblast", "Mesoderm", "Endoderm", "Ectoderm"))
#                       ,]
coldata <- data.frame(colData(study_mae))
# coldata$lineage10x_2[is.na(coldata$lineage10x_2)] <- "Unknown"
```

```{r}
lapply(named_list(unique(coldata$stage)), function(stage){
  table(coldata[coldata$stage == stage,]$lineage10x_2)
})
# $E5.5
#          Epiblast Visceral_endoderm 
#                84                24 
# $E4.5
#           Epiblast Primitive_endoderm 
#                 60                 43 
# $E6.5
#          Epiblast      ExE_ectoderm          Mesoderm  Primitive_Streak Visceral_endoderm 
#               146                 8                28                43                45 
# $E7.5
#         Ectoderm         Endoderm         Epiblast         Mesoderm Primitive_Streak 
#               43               81               44              141               33 
```
